apiVersion: apps/v1
kind: Deployment
metadata:
  name: deerghanshu11
spec:
  selector:
    matchLabels:
      app: deerghanshu11-pod
  template:
    metadata:
      labels:
        app: deerghanshu11-pod
    spec:
      containers:
      - name: deerghanshu11-container
        image: cloudnativeacr01.azurecr.io/deerghanshu11:v1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000


