apiVersion: apps/v1
kind: Deployment
metadata:
  name: dscloudaction
spec:
  selector:
    matchLabels:
      app: dscloudaction-pod
  template:
    metadata:
      labels:
        app: dscloudaction-pod
    spec:
      containers:
      - name: dscloudaction-container
        image: cloudnativeacr01.azurecr.io/dscloudaction:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000


